name: read_excel_polars_openpyxl
version: 1.0.0
category: IO
tier: lazy
cluster: data_pipeline
priority: 55
purpose: Load Excel files with openpyxl + polars through canonical wrapper execution
triggers:
  keywords:
  - read excel fast
  - polars excel
  - openpyxl read
  - performance excel
  - batch spreadsheet
  match_extensions:
  - .xlsx
  - .xls
  match_phases:
  - ingest
  match_errors:
  - MemoryError
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: read_excel_polars_openpyxl.md
token_estimate: 260
execution:
  entrypoint: agents/tools/wrappers/read_excel_polars_openpyxl_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill read_excel_polars_openpyxl
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      sheet_name:
        anyOf:
        - type: string
        - type: integer
      read_only:
        type: boolean
      data_only:
        type: boolean
      use_columns:
        type: array
      preview_rows:
        type: integer

