name: log_bundle_folder_management
version: 1.0.0
category: Observability
tier: lazy
cluster: observability
priority: 45
purpose: Log folders outside PyInstaller bundles
triggers:
  keywords:
  - log folder
  - bundle logs
  - pyinstaller logs
  - _MEIPASS
  match_extensions: []
  match_phases:
  - execute
  match_errors: []
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: log_bundle_folder_management.md
token_estimate: 260
execution:
  entrypoint: agent_tools/wrappers/log_bundle_folder_management_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill log_bundle_folder_management --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      app_name:
        type: string
      bundled_mode:
        type: boolean
      create_if_missing:
        type: boolean
      validate_writable:
        type: boolean
      fallback_to_temp:
        type: boolean
      log_folder_path:
        type: string
      bundle_root:
        type: string
      dry_run:
        type: boolean
