name: log_overwrite_policy
version: 1.0.0
category: Observability
tier: lazy
cluster: observability
priority: 45
purpose: Fresh logs per execution, no accumulation
triggers:
  keywords:
  - log overwrite
  - fresh log
  - execution log
  match_extensions: []
  match_phases:
  - execute
  match_errors: []
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: log_overwrite_policy.md
token_estimate: 240
execution:
  entrypoint: agent_tools/wrappers/log_overwrite_policy_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill log_overwrite_policy --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      log_file_path:
        type: string
      encoding:
        type: string
      create_parent:
        type: boolean
      header_lines:
        type: array
        items:
          type: string
      dry_run:
        type: boolean
