name: load_yaml_files
version: 1.0.0
category: Formats
tier: lazy
cluster: format_loaders
priority: 50
purpose: Load and validate YAML files through canonical wrapper execution
triggers:
  keywords:
  - load yaml
  - yaml config
  - parse yaml
  - yaml file
  - read yaml
  match_extensions:
  - .yaml
  - .yml
  match_phases:
  - config
  - ingest
  match_errors:
  - YAMLError
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: load_yaml_files.md
token_estimate: 220
execution:
  entrypoint: agent_tools/wrappers/load_yaml_files_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill load_yaml_files
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      encoding:
        type: string
