# Layer 2 Header — path_traversal_prevention
name: path_traversal_prevention
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 92
purpose: "Prevents path traversal attacks and sandbox escapes"
triggers:
  keywords: [path traversal, directory escape, sandbox boundary, path validation, security path]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "path_traversal_prevention.md"
token_estimate: 500
execution:
  entrypoint: "agents/tools/wrappers/policy_guidance_wrapper.py::run"
  command: ".venv/Scripts/python.exe agents/tools/run_wrapper.py --skill path_traversal_prevention --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

