# Layer 2 Header — scope_control_discipline
name: scope_control_discipline
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 98
purpose: "Strict scope boundaries preventing scope creep"
triggers:
  keywords: [scope control, scope creep, out of scope, boundary enforcement, authorized changes]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "scope_control_discipline.md"
token_estimate: 500
execution:
  entrypoint: "agents/tools/wrappers/policy_guidance_wrapper.py::run"
  command: ".venv/Scripts/python.exe agents/tools/run_wrapper.py --skill scope_control_discipline --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

