name: context_loading_protocol
version: 1.0.0
category: Planning
tier: core
cluster: planning_pipeline
priority: 90
purpose: 'Loads context: treemap first, then dependencies, then task-specific'
triggers:
  keywords:
  - load context
  - context loading
  - treemap
  - dependencies report
  - project context
  - initialize context
  match_extensions: []
  match_phases:
  - init
  - bootstrap
  match_errors: []
requires: []
exclusive_with: []
pipeline: planning
pipeline_order: 1
modes:
- ANALYZE_AND_IMPLEMENT
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
body_file: context_loading_protocol.md
token_estimate: 800
execution:
  entrypoint: agents/tools/wrappers/policy_guidance_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill context_loading_protocol
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

