name: output_validation_checklist
version: 1.0.0
category: Planning
tier: core
cluster: planning_pipeline
priority: 87
purpose: Validates outputs before emission — plan IDs, versions, DAG dependencies
triggers:
  keywords:
  - validate output
  - output checklist
  - plan validation
  - schema check
  - pre-emission check
  match_extensions: []
  match_phases:
  - validate
  match_errors: []
requires:
- risk_scoring_matrix
exclusive_with: []
pipeline: planning
pipeline_order: 4
modes:
- ANALYZE_AND_IMPLEMENT
agent_binding:
  mandatory:
  - agent_inspector
  optional:
  - agent_executor
  - agent_senior
body_file: output_validation_checklist.md
token_estimate: 700
execution:
  entrypoint: agents/tools/wrappers/policy_guidance_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill output_validation_checklist
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

