name: db_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore local SQLite/DuckDB schema through canonical wrapper execution
triggers:
  keywords:
  - database
  - db file
  - inspect database
  - list tables
  - explore duckdb
  match_extensions:
  - .db
  - .sqlite
  - .duckdb
  match_phases:
  - analyze
  match_errors:
  - sqlite3.Error
  - duckdb.Error
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: db_explorer.md
token_estimate: 240
execution:
  entrypoint: agent_tools/wrappers/db_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill db_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      read_only:
        type: boolean
      table:
        type: string
      preview_rows:
        type: integer
