name: file_explorer
version: "1.0.0"
category: File Exploration
tier: core
cluster: file_exploration
priority: 75
purpose: "Unified facade: detects file type, delegates to format-specific explorer"
triggers:
  keywords: [explore file, inspect file, file info, file metadata, analyze file, what is this file]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
role: facade
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_senior]
  optional: [agent_executor]
body_file: "file_explorer.md"
token_estimate: 600
