name: html_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore HTML metadata and content preview through canonical wrapper execution
triggers:
  keywords:
  - html
  - inspect html
  - parse html
  - explore webpage
  match_extensions:
  - .html
  - .htm
  match_phases:
  - analyze
  - ingest
  match_errors: []
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: html_explorer.md
token_estimate: 220
execution:
  entrypoint: agent_tools/wrappers/html_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill html_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      encoding:
        type: string
      preview_chars:
        type: integer
