name: yaml_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore YAML structure through canonical wrapper execution
triggers:
  keywords:
  - yaml
  - yml
  - inspect yaml
  - parse yaml
  - explore yaml
  match_extensions:
  - .yaml
  - .yml
  match_phases:
  - analyze
  - ingest
  match_errors:
  - YAMLError
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: yaml_explorer.md
token_estimate: 220
execution:
  entrypoint: agent_tools/wrappers/yaml_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill yaml_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      encoding:
        type: string
      schema_depth:
        type: integer
      max_items:
        type: integer
