name: skill_builder
tier: core
cluster: meta
priority: 95
purpose: "Allows the agent to self-improve by creating and registering new skills."
checks:
  - "User approval required for 'safe_mode' (not implemented yet)"

triggers:
  match_phases:
    - plan
    - improvement
  match_keywords:
    - "create skill"
    - "build tool"
    - "generate wrapper"
    - "implement capability"

# The implementation wrapper
wrapper_path: agents/tools/wrappers/skill_builder_wrapper.py
execution:
  entrypoint: agents/tools/wrappers/skill_builder_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill skill_builder --args-json '<json-object>'

