name: skill_merger
tier: core
cluster: meta
priority: 90
purpose: "Consolidates multiple skills into one and deletes redundancy."
triggers:
  match_phases:
    - improvement
    - maintenance
  match_keywords:
    - "merge skills"
    - "consolidate tools"
    - "cleanup registry"
    - "remove redundancy"

# The implementation wrapper
wrapper_path: agents/tools/wrappers/skill_merger_wrapper.py
execution:
  entrypoint: agents/tools/wrappers/skill_merger_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill skill_merger --args-json '<json-object>'

