name: type_master
version: 1.0.0
category: Python
tier: lazy
cluster: python_quality
priority: 60
purpose: Type hints, Mypy/Pyright, Pydantic runtime validation
triggers:
  keywords:
  - type hint
  - typing
  - mypy
  - pyright
  - pydantic
  - type annotation
  - type safety
  match_extensions:
  - .py
  match_phases: []
  match_errors:
  - TypeError
  - ValidationError
requires: []
exclusive_with: []
modes:
- ANALYZE_AND_IMPLEMENT
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_senior
  - agent_executor
  optional:
  - agent_inspector
max_phase: 1
body_file: type_master.md
token_estimate: 800
execution:
  entrypoint: agents/tools/wrappers/python_quality_advisor_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill type_master
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

