name: async_concurrency_expert
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 55
purpose: "Async/await, event loops, concurrent task handling"
triggers:
  keywords: ["async_concurrency_expert", "async concurrency expert", "async"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "async_concurrency_expert.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/python_quality_advisor_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill async_concurrency_expert --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
