name: code_analysis_qa_gate
version: 1.0.0
category: Python
tier: lazy
cluster: python_quality
priority: 64
purpose: Static code analysis and QA gate definition for pre-merge quality enforcement
triggers:
  keywords:
  - code analysis
  - static analysis
  - qa gate
  - quality gate
  - lint gate
  - type check
  - maintainability
  match_extensions:
  - .py
  match_phases:
  - validate
  - test
  match_errors:
  - LintError
  - mypy
requires:
- linter_formatter_guru
exclusive_with: []
modes:
- ANALYZE_AND_IMPLEMENT
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_senior
  - agent_executor
  optional:
  - agent_inspector
max_phase: 1
body_file: code_analysis_qa_gate.md
token_estimate: 1350
execution:
  entrypoint: agent_tools/wrappers/python_quality_advisor_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill code_analysis_qa_gate
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
