# Layer 2 Header - code_analysis_qa_gate
name: code_analysis_qa_gate
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 64
purpose: "Static code analysis and QA gate definition for pre-merge quality enforcement"
triggers:
  keywords: [code analysis, static analysis, qa gate, quality gate, lint gate, type check, maintainability]
  match_extensions: [".py", ".yaml", ".toml"]
  match_phases: [plan, test, validate]
  match_errors: [LintError, TypeError]
requires: [linter_formatter_guru]
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT, IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_senior, agent_executor]
  optional: [agent_inspector]
  # NOT agent_junior - this skill requires policy and threshold calibration
max_phase: 1
body_file: "code_analysis_qa_gate.md"
token_estimate: 1350
