name: code_structuring_pythonic
version: "1.0.0"
category: Python
tier: core
cluster: python_quality
priority: 70
purpose: "Idiomatic Python patterns, PEP 8 compliance, clean architecture"
triggers:
  keywords: [pythonic, pep 8, code structure, clean code, code smell, anti-pattern, idiomatic python]
  match_extensions: [".py"]
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
scope: module
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
body_file: "code_structuring_pythonic.md"
token_estimate: 800
execution:
  entrypoint: "agent_tools/wrappers/python_quality_advisor_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill code_structuring_pythonic --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
