name: dependency_audit
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 50
purpose: "Security vulns, compatibility, licensing audit"
triggers:
  keywords: ["dependency_audit", "dependency audit", "dependency"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "dependency_audit.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/dependency_audit_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill dependency_audit --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
