name: externalized_logic_handler
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 45
purpose: "Externalize logic into rules, DSLs, config-driven templates"
triggers:
  keywords: ["externalized_logic_handler", "externalized logic handler", "externalized"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "externalized_logic_handler.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/externalized_logic_handler_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill externalized_logic_handler --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
