name: microservices_api_architect
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 50
purpose: "FastAPI/Flask APIs with DDD and OpenAPI"
triggers:
  keywords: ["microservices_api_architect", "microservices api architect", "microservices"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "microservices_api_architect.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/microservices_api_architect_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill microservices_api_architect --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
