name: naming_control_flow
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 45
purpose: "Naming conventions and readable control flow patterns"
triggers:
  keywords: ["naming_control_flow", "naming control flow", "naming"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "naming_control_flow.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/python_quality_advisor_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill naming_control_flow --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
