# Layer 2 Header — performance_profiler
name: performance_profiler
version: "1.0.0"
category: Python
tier: lazy
cluster: python_quality
priority: 50
purpose: "cProfile, line_profiler, memory_profiler optimization"
triggers:
  keywords: [performance, profiling, slow, memory, optimization, bottleneck, cProfile]
  match_extensions: [".py"]
  match_phases: []
  match_errors: [MemoryError, TimeoutError]
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_senior]
  optional: [agent_inspector]
  # NOT agent_junior — performance analysis requires senior judgment
  # NOT agent_executor — profiling is analysis, not execution
max_phase: 1  # Blocked from Phase 0
body_file: "performance_profiler.md"
token_estimate: 1500
