name: regression_test_automation
version: 1.0.0
category: Python
tier: lazy
cluster: python_quality
priority: 63
purpose: Automated regression testing workflow with baseline capture, targeted suites,
  and stability checks
triggers:
  keywords:
  - regression test
  - automatic regression
  - prevent regressions
  - flaky tests
  - smoke suite
  - test matrix
  match_extensions:
  - .py
  match_phases:
  - test
  match_errors:
  - AssertionError
  - test failed
  - flaky
requires:
- testing_qa_mentor
exclusive_with: []
modes:
- ANALYZE_AND_IMPLEMENT
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_senior
  - agent_executor
  optional:
  - agent_inspector
max_phase: 1
body_file: regression_test_automation.md
token_estimate: 1400
execution:
  entrypoint: agent_tools/wrappers/python_quality_advisor_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill regression_test_automation
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
