name: excel_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore workbook sheets and previews through canonical wrapper execution
triggers:
  keywords:
  - excel
  - spreadsheet
  - workbook
  - inspect xlsx
  - explore sheet
  match_extensions:
  - .xlsx
  - .xls
  match_phases:
  - analyze
  - ingest
  match_errors:
  - FileNotFoundError
  - ValueError
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: excel_explorer.md
token_estimate: 220
execution:
  entrypoint: agents/tools/wrappers/excel_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill excel_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      sheet_name:
        anyOf:
        - type: string
        - type: integer
      read_only:
        type: boolean
      data_only:
        type: boolean
      preview_rows:
        type: integer

