name: pdf_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore PDF metadata and page previews through canonical wrapper execution
triggers:
  keywords:
  - pdf
  - inspect pdf
  - extract pdf text
  - explore pdf
  match_extensions:
  - .pdf
  match_phases:
  - analyze
  match_errors: []
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: pdf_explorer.md
token_estimate: 220
execution:
  entrypoint: agents/tools/wrappers/pdf_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill pdf_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      preview_pages:
        type: integer
      preview_chars:
        type: integer

