name: powerbi_explorer
version: 1.0.0
category: File Exploration
tier: lazy
cluster: file_exploration
priority: 50
purpose: Explore Power BI package structure through canonical wrapper execution
triggers:
  keywords:
  - power bi
  - pbix
  - pbit
  - inspect powerbi
  - explore report model
  match_extensions:
  - .pbix
  - .pbit
  match_phases:
  - analyze
  match_errors: []
requires:
- file_explorer
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_inspector
  - agent_senior
  optional:
  - agent_executor
max_phase: 2
body_file: powerbi_explorer.md
token_estimate: 220
execution:
  entrypoint: agents/tools/wrappers/powerbi_explorer_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill powerbi_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      preview_chars:
        type: integer

