name: execution_flow_orchestration
version: "1.0.0"
category: Execution
tier: core
cluster: execution_pipeline
priority: 86
purpose: "Structured execution with atomic actions, progress monitoring, failure handling"
triggers:
  keywords: [execute plan, orchestrate, workflow execution, run pipeline, coordinate tasks]
  match_extensions: []
  match_phases: [execute]
  match_errors: []
requires: [output_validation_checklist]
exclusive_with: []
pipeline: execution
pipeline_order: 1
modes: [ANALYZE_AND_IMPLEMENT, IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor]
  optional: [agent_senior]
body_file: "execution_flow_orchestration.md"
token_estimate: 1000
