name: git_rollback_strategy
version: "1.0.0"
category: Execution
tier: core
cluster: execution_pipeline
priority: 84
purpose: "Git revert for rollback maintaining commit history"
triggers:
  keywords: [rollback, git revert, undo commit, revert changes, restore previous]
  match_extensions: []
  match_phases: [rollback]
  match_errors: [rollback_required]
requires: [execution_flow_orchestration]
exclusive_with: []
pipeline: execution
pipeline_order: 2
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor]
  optional: [agent_senior]
body_file: "git_rollback_strategy.md"
token_estimate: 600
