name: plan_archive_protocol
version: "1.0.0"
category: Execution
tier: core
cluster: execution_pipeline
priority: 83
purpose: "Archives active plans before new execution preserving history"
triggers:
  keywords: [archive plan, plan history, preserve plan, plan lifecycle, plan versioning]
  match_extensions: []
  match_phases: [pre-execute]
  match_errors: []
requires: []
exclusive_with: []
pipeline: execution
pipeline_order: 0
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor]
  optional: []
body_file: "plan_archive_protocol.md"
token_estimate: 500
execution:
  entrypoint: "agent_tools/wrappers/policy_guidance_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill plan_archive_protocol --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
