name: connect_duckdb
version: 1.0.0
category: Database
tier: lazy
cluster: data_pipeline
priority: 55
purpose: Establish and validate DuckDB connections through canonical wrapper execution
triggers:
  keywords:
  - duckdb
  - connect database
  - analytical database
  - olap
  - duckdb connection
  match_extensions:
  - .db
  - .duckdb
  - .sql
  match_phases:
  - ingest
  - transform
  match_errors:
  - duckdb.Error
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: connect_duckdb.md
token_estimate: 250
execution:
  entrypoint: agents/tools/wrappers/connect_duckdb_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill connect_duckdb
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - database_path
    properties:
      database_path:
        type: string
      read_only:
        type: boolean
      config:
        type: object

