# Layer 2 Header - debugger_orchestrator
name: debugger_orchestrator
version: "1.0.0"
category: Debugging
tier: lazy
cluster: debugging
priority: 67
purpose: "End-to-end debugger workflow: triage, reproduce, isolate, verify, and regression-proof"
triggers:
  keywords: [debugger, debug workflow, incident triage, reproduce bug, isolate failure, fix verification]
  match_extensions: [".py", ".log", ".json"]
  match_phases: [test, validate]
  match_errors: [Traceback, Exception, Error, "test failed"]
requires: [systematic_debugging]
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_senior]
  optional: [agent_inspector]
  # NOT agent_junior - this skill assumes multi-step technical diagnosis
  # NOT agent_executor - executor should run approved actions, not broad investigation
max_phase: 1
body_file: "debugger_orchestrator.md"
token_estimate: 1500
execution:
  entrypoint: "agent_tools/wrappers/policy_guidance_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill debugger_orchestrator --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
