# Layer 2 Header — root_cause_tracing
name: root_cause_tracing
version: "1.0.0"
category: Debugging
tier: lazy
cluster: debugging
priority: 60
purpose: "5-step backward call stack tracing to find original trigger"
triggers:
  keywords: [root cause, call stack, traceback, deep bug, propagation, origin]
  match_extensions: []
  match_phases: []
  match_errors: [Traceback]
requires: [systematic_debugging]  # Should load after systematic_debugging
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_senior]
  optional: []
  # NOT agent_junior, NOT agent_executor, NOT agent_inspector (deep debugging is senior-only)
max_phase: 1  # Blocked from Phase 0
body_file: "root_cause_tracing.md"
token_estimate: 1300
