name: brainstorming_design_explorer
version: 1.0.0
category: Planning
tier: core
cluster: planning_pipeline
priority: 80
purpose: Pre-planning design exploration with 2-3 approaches and YAGNI enforcement
triggers:
  keywords:
  - brainstorm
  - design exploration
  - explore approaches
  - what to build
  - ideation
  - trade-off analysis
  match_extensions: []
  match_phases:
  - design
  match_errors: []
requires: []
exclusive_with: []
modes:
- ANALYZE_AND_IMPLEMENT
agent_binding:
  mandatory:
  - agent_inspector
  optional:
  - agent_senior
body_file: brainstorming_design_explorer.md
token_estimate: 1000
execution:
  entrypoint: agent_tools/wrappers/policy_guidance_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill brainstorming_design_explorer
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
