name: decision_process_flow
version: "1.0.0"
category: Planning
tier: core
cluster: planning_pipeline
priority: 89
purpose: "Structured decision-making: validation, impact analysis, scoring, plan generation"
triggers:
  keywords: [decision process, make decision, evaluate options, plan generation, impact analysis]
  match_extensions: []
  match_phases: [plan]
  match_errors: []
requires: [context_loading_protocol]
exclusive_with: []
pipeline: planning
pipeline_order: 2
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector]
  optional: [agent_senior]
body_file: "decision_process_flow.md"
token_estimate: 1200
