name: decision_process_flow
version: 1.0.0
category: Planning
tier: core
cluster: planning_pipeline
priority: 89
purpose: 'Structured decision-making: validation, impact analysis, scoring, plan generation'
triggers:
  keywords:
  - decision process
  - make decision
  - evaluate options
  - plan generation
  - impact analysis
  match_extensions: []
  match_phases:
  - plan
  match_errors: []
requires:
- context_loading_protocol
exclusive_with: []
pipeline: planning
pipeline_order: 2
modes:
- ANALYZE_AND_IMPLEMENT
agent_binding:
  mandatory:
  - agent_inspector
  optional:
  - agent_senior
body_file: decision_process_flow.md
token_estimate: 1200
execution:
  entrypoint: agent_tools/wrappers/policy_guidance_wrapper.py::run
  command: .venv/Scripts/python.exe agent_tools/run_wrapper.py --skill decision_process_flow
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
