name: output_validation_checklist
version: "1.0.0"
category: Planning
tier: core
cluster: planning_pipeline
priority: 87
purpose: "Validates outputs before emission — plan IDs, versions, DAG dependencies"
triggers:
  keywords: [validate output, output checklist, plan validation, schema check, pre-emission check]
  match_extensions: []
  match_phases: [validate]
  match_errors: []
requires: [risk_scoring_matrix]
exclusive_with: []
pipeline: planning
pipeline_order: 4
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector]
  optional: [agent_executor, agent_senior]
body_file: "output_validation_checklist.md"
token_estimate: 700
