name: risk_scoring_matrix
version: "1.0.0"
category: Planning
tier: core
cluster: planning_pipeline
priority: 88
purpose: "3x4 probability/impact risk matrix with approval thresholds"
triggers:
  keywords: [risk assessment, risk score, risk matrix, probability impact, risk level]
  match_extensions: []
  match_phases: [plan]
  match_errors: []
requires: [decision_process_flow]
exclusive_with: []
pipeline: planning
pipeline_order: 3
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector]
  optional: [agent_senior]
body_file: "risk_scoring_matrix.md"
token_estimate: 900
