name: ui_identity_policy
version: "1.0.0"
category: UI
tier: lazy
cluster: ui
priority: 45
purpose: "App identity (name, version) without redundancy"
triggers:
  keywords: ["ui_identity_policy", "ui identity policy", "ui"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "ui_identity_policy.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/ui_identity_policy_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill ui_identity_policy --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
