name: ui_splash_and_lazy_loading
version: "1.0.0"
category: UI
tier: lazy
cluster: ui
priority: 45
purpose: "Splash screens during resource loading"
triggers:
  keywords: ["ui_splash_and_lazy_loading", "ui splash and lazy loading", "ui"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "ui_splash_and_lazy_loading.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/ui_splash_and_lazy_loading_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill ui_splash_and_lazy_loading --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
