name: ui_theme_binding
version: "1.0.0"
category: UI
tier: lazy
cluster: ui
priority: 50
purpose: "Reactive theme system with light/dark mode"
triggers:
  keywords: ["ui_theme_binding", "ui theme binding", "ui"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "ui_theme_binding.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/ui_theme_binding_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill ui_theme_binding --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties: {}
