name: ui_widget_modularity
version: "1.0.0"
category: UI
tier: lazy
cluster: ui
priority: 50
purpose: "Self-contained, reusable, decoupled widgets"
triggers:
  keywords: ["ui_widget_modularity", "ui widget modularity", "ui"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "ui_widget_modularity.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/ui_advisor_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill ui_widget_modularity --args-json '<json-object>'"
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer
