name: input_validation_sanitizer
version: "1.0.0"
category: File Handling
tier: dormant
cluster: file_handling
priority: 50
purpose: "Input validation and sanitization"
triggers:
  keywords: ["input_validation_sanitizer", "input validation sanitizer", "input"]
  match_extensions: []
  match_phases: [implement]
  match_errors: []
requires: []
exclusive_with: []
modes: [IMPLEMENT_ONLY]
agent_binding:
  mandatory: [agent_executor, agent_senior]
  optional: [agent_inspector]
max_phase: 2
body_file: "input_validation_sanitizer.md"
token_estimate: 220
execution:
  entrypoint: "agent_tools/wrappers/input_validation_sanitizer_wrapper.py::run"
  command: ".venv/Scripts/python.exe agent_tools/run_wrapper.py --skill input_validation_sanitizer --args-json '<json-object>'"
  args_schema:
    type: object
    required: [value]
    properties:
      value: {}
      expected_type:
        type: string
      strip_strings:
        type: boolean
      allow_empty:
        type: boolean
      min_length:
        type: integer
      max_length:
        type: integer
      min_value:
        type: number
      max_value:
        type: number
      allowed_values:
        type: array
      pattern:
        type: string
