name: execution_flow_orchestration
version: 1.0.0
category: Execution
tier: core
cluster: execution_pipeline
priority: 86
purpose: Structured execution with atomic actions, progress monitoring, failure handling
triggers:
  keywords:
  - execute plan
  - orchestrate
  - workflow execution
  - run pipeline
  - coordinate tasks
  match_extensions: []
  match_phases:
  - execute
  match_errors: []
requires:
- output_validation_checklist
exclusive_with: []
pipeline: execution
pipeline_order: 1
modes:
- ANALYZE_AND_IMPLEMENT
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  optional:
  - agent_senior
body_file: execution_flow_orchestration.md
token_estimate: 1000
execution:
  entrypoint: agents/tools/wrappers/policy_guidance_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill execution_flow_orchestration
    --args-json '<json-object>'
  args_schema:
    type: object
    required: []
    properties:
      objective:
        type: string
      target_paths:
        type: array
        items:
          type: string
      constraints:
        type: array
        items:
          type: string
      output_mode:
        type: string
      max_items:
        type: integer

