name: load_json_files
version: 1.0.0
category: Formats
tier: lazy
cluster: format_loaders
priority: 50
purpose: Load and validate JSON files through canonical wrapper execution
triggers:
  keywords:
  - load json
  - json config
  - parse json
  - json file
  - read json
  match_extensions:
  - .json
  match_phases:
  - config
  - ingest
  match_errors:
  - JSONDecodeError
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: load_json_files.md
token_estimate: 220
execution:
  entrypoint: agents/tools/wrappers/load_json_files_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill load_json_files
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      encoding:
        type: string

