name: load_sql_queries
version: 1.0.0
category: Formats
tier: lazy
cluster: format_loaders
priority: 50
purpose: Load SQL query files through canonical wrapper execution
triggers:
  keywords:
  - load sql
  - sql file
  - query template
  - sql loader
  - reusable query
  match_extensions:
  - .sql
  match_phases:
  - ingest
  match_errors: []
requires: []
exclusive_with: []
modes:
- IMPLEMENT_ONLY
agent_binding:
  mandatory:
  - agent_executor
  - agent_senior
  optional:
  - agent_inspector
max_phase: 2
body_file: load_sql_queries.md
token_estimate: 240
execution:
  entrypoint: agents/tools/wrappers/load_sql_queries_wrapper.py::run
  command: .venv/Scripts/python.exe agents/tools/run_wrapper.py --skill load_sql_queries
    --args-json '<json-object>'
  args_schema:
    type: object
    required:
    - path
    properties:
      path:
        type: string
      encoding:
        type: string
      strip_comments:
        type: boolean
      preview_chars:
        type: integer

