# Layer 2 Header — ambiguity_escalation
name: ambiguity_escalation
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 94
purpose: "Escalates unclear requirements instead of guessing"
triggers:
  keywords: [unclear requirement, ambiguous request, escalate, need clarification, uncertain scope]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "ambiguity_escalation.md"
token_estimate: 500
