# Layer 2 Header — artifact_persistence_discipline
name: artifact_persistence_discipline
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 96
purpose: "Agent outputs persisted to disk, never deleted"
triggers:
  keywords: [persist artifact, save output, artifact history, do not delete, audit trail]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "artifact_persistence_discipline.md"
token_estimate: 500
