# Layer 2 Header — protected_file_validation
name: protected_file_validation
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 93
purpose: "Validates protected files on blacklist are not modified"
triggers:
  keywords: [protected file, immutability blacklist, file protection, cannot modify, blacklisted file]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "protected_file_validation.md"
token_estimate: 500
