# Layer 2 Header — workspace_model_awareness
name: workspace_model_awareness
version: "1.0.0"
category: Governance
tier: core
cluster: governance
priority: 99
purpose: "Agents respect workspace model — agent/ writable, source protected"
triggers:
  keywords: [workspace model, workspace boundaries, agent workspace, writable directory, protected code]
  match_extensions: []
  match_phases: []
  match_errors: []
requires: []
exclusive_with: []
modes: [ANALYZE_AND_IMPLEMENT]
agent_binding:
  mandatory: [agent_inspector, agent_executor, agent_senior]
  optional: []
body_file: "workspace_model_awareness.md"
token_estimate: 500
